### ISSUE TITLE
Home page pictures and gallery

### ISSUE THREAD

**Issue by Technius** [xournalpp/xournalpp.github.io#18]
It would be nice to have some pictures on the front page to show what Xournal++ looks like.

We should also add a gallery demonstrating various features of Xournal++.

I'm not sure about file hosting though. I don't think it would be a good idea to put images on this repo, so it would be better if we could find some free open-source-friendly file hosting service.

**Comment by rolandlo** [comment]
This would be in perfect accordance with #5:

>  looks visually appealing and gives a visual impression how working with Xournal++ looks like

Why do you think that putting images in the repo would be a bad idea? This seems to be the recommended way by mkdocs. Is it just a question of storage size?

**Comment by Technius** [comment]
Images tend to be large and have to live in git history, which means they'll be there even after they're deleted.

**Comment by LittleHuba** [comment]
You could use git-lfs for this. It handles large files in the git history better than if you just upload them with git.

**Comment by Technius** [comment]
`git-lfs` doesn't work with Pages, but maybe it'll be cloned automatically when Actions builds the website? I'll try it out tomorrow.

**Comment by rolandlo** [comment]
What about doing it like with the screenshots linked in the appdata xml https://github.com/xournalpp/xournalpp/pull/3094, namely to have them stored under some `user-images.githubusercontent.com` adress (by opening an issue and adding the image)? From the experience we had witlh `git-lfs` (where bandwidth of 1GB/month didn't suffice anywhere nearly), this may be preferable to `git-lfs`.

**Comment by LittleHuba** [comment]
Interesting idea... Though I'm not quite sure if this is a great idea in the long run. 

All in all I don't think images are a major problem for git in itself, since website pictures need to be compressed anyway. So we are talking about a maximum of 2MB per picture. 

Further the main problem of big files in repos is cloning to your own machine, which nobody needs to do for this repo.

I think simply adding pictures to the normal git repo is absolutely sufficient for our use case. No git-lfs, no hacks, just plain old git.

**Comment by rolandlo** [comment]
Ok, then let's use plain old git for the pictures.

**Comment by LittleHuba** [comment]
I think this is solved by #49
