### ISSUE TITLE
How to exit from presentation mode

### ISSUE THREAD

**Issue by MrFahim123** [xournalpp/xournalpp.github.io#92]
i don't know the key to exit from presentation mode

**Comment by tmoerschell** [comment]
Since the menu bar isn't visible in presentation mode, you have two other options left: pressing _F5_ or clicking on the corresponding button on the bottom right of the screen (computer seen from the top with a dot in front). 

Please keep in mind that such matters don't belong on the website's GitHub issues, but rather on the app's discussion forum: https://github.com/xournalpp/xournalpp/discussions
